environment      = "preprod"
aws_region       = "us-east-1"
container_cpu    = 256
container_memory = 512
desired_count    = 1
# github_org       = "your-github-org"
github_repo      = "github.com/reponame"
encryption_type  = "AES256"
endpoint         = "preprod@gmail.com"
