environment      = "prod"
aws_region       = "us-east-2"
container_cpu    = 512
container_memory = 1024
desired_count    = 2
# github_org       = "your-github-org"
github_repo      = "github.com/reponame/"
encryption_type  = "KMS"
endpoint         = "prod@gmail.com"